# -*- mode: ruby -*-

# vi: set ft=ruby :

#We will add the 16.04 version of ubuntu

#And change the disk space from 10 GB to 30 GB

Vagrant.configure("2") do |config|

config.vm.box = "ubuntu/bionic64"

config.disksize.size = "20GB"

#Stop automatic updates. Tur it to true or commet it out to have guest additios automatically uodated  
config.vbguest.auto_update = false
  
#We will share the Downloads folder from the Windows host machine with Ubuntu guest OS #from our virtual machine

#Make sure to change this path with the one coresponding to your computer !!!!!!!!!!!!!!!!!!

#This will help us share the Downloads folder from the Windows machine with the virtual

#machine. But on the guest machine the Downloads folder will be found as vagrant_data

#for Windows use next line ! - comment out next line if you are using macOS or Ubuntu!!!!!!!!!!

config.vm.synced_folder "C:/Users/your_user_name/Downloads", "/vagrant_data"

#For macOS and Ubuntu  uncomment next line !!!!!!! And comment out if using Windows as host OS

#config.vm.synced_folder "/Users/your_user_name/Downloads", "/vagrant_data"

#This is where we pass the bootstrap.sh file so that Vagrant can run install all we need in the #machine.

config.vm.provision :shell, path: "bootstrap.sh"

# Add the VirtualBox machine:

config.vm.provider "virtualbox" do |vb|

# # Display the VirtualBox GUI when booting the machine

vb.gui = true

# Customize the amount of memory on the VM:

vb.memory = "2048"
#vb.memory = "4096"

# set cpu’s  

vb.cpus = 1
#vb.cpus = 4


#Enable biderectional “copy/paste” and “drag and drop”

vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']

vb.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']

end

end
